### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ginpen1** [ginpen1/furima-34780#9]
# URL
https://furima-34780.herokuapp.com/

# Basic認証のIDとパスワード
- ID
takuyakurohama
- パスワード
2412

# 出品者用のメールアドレスとパスワード
- メールアドレス
test@123
- パスワード
test123

# 購入者用のメールアドレスとパスワード
- メールアドレス
test@234
- パスワード
test234

**Comment by snkw-works** [comment]
@ginpen1 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/113231688-c6bf1400-92d6-11eb-8fe7-34e7fc316dd0.png)
